import { programSchema, type Program } from "./domain";

const sources = {
  pku: "https://www.isd.pku.edu.cn/en/detail.php?id=818",
  fudan: "https://iso.fudan.edu.cn/_upload/article/files/bc/ed/37f712cb4e3f8316f4ec2ebc4ba2/6c9fce5d-d137-4934-b484-1c4630f18aa5.pdf",
  sjtu: "https://gc.sjtu.edu.cn/admission/international-undergraduate-admission/application-requirements/",
  zju: "https://iczu.zju.edu.cn/admissionsen/2024/1030/c68988a2981659/page.htm",
  xmu: "https://admissions.xmu.edu.cn/Admissions/Undergraduate_Students.htm",
  tongji: "https://study.tongji.edu.cn/__local/6/AE/A6/66E0A7D71A250672DFF40ED4048_3682FBF2_3762E.pdf",
  ecnu: "https://lxs.ecnu.edu.cn/en_admission_degree_programs_undergraduate_program/",
  blcu: "https://admission.blcu.edu.cn/en/384/list.htm",
  uibe: "https://sie.uibe.edu.cn/en/Prgr/BacDegPro/OfEn/d56a3c4fd73446e9803fb0e0b1345f4a.htm",
  sdufe: "https://sie.sdufe.edu.cn/info/1209/79441.htm",
};
const documents = ["หนังสือเดินทางและรูปถ่าย", "วุฒิมัธยมปลายและ Transcript พร้อมคำแปลจีนหรืออังกฤษ", "หลักฐานผลสอบภาษา", "ตรวจเอกสารเฉพาะสาขาจากประกาศต้นฉบับ"];
function record(p: Partial<Program> & Pick<Program,"id"|"universityId"|"university"|"chineseName"|"name"|"city"|"source">): Program {
  return programSchema.parse({ country:"China", kind:"program", language:"Chinese", years:null, intake:"2026", subject:"หลายสาขา", tuition:null, currency:"CNY", feeYear:"2026", feeNote:"ยังไม่ยืนยันค่าเรียนเฉพาะสาขา", opensAt:"", deadline:"", deadlineNote:"ยังไม่ยืนยันกำหนดรอบถัดไป", ielts:null, minBand:null, hskLevel:null, hskScore:null, languageValidityYears:null, languageNote:"ตรวจเกณฑ์ภาษาเฉพาะสาขาและข้อยกเว้นจากต้นฉบับ", csca:"unknown", cscaNote:"ตรวจรายวิชา CSCA ของสาขาที่สมัคร", academicNote:"ต้องตรวจวุฒิมัธยมปลาย สัญชาติ อายุ และเงื่อนไขเฉพาะสาขากับมหาวิทยาลัย", description:"", documents, scholarships:[], requirementsSource:p.source, checkedAt:"2026-09-16", verification:"partial", reviewNote:"ตรวจประกาศที่อ้างอิงแล้วบางส่วน รอบ 2027 ต้องยืนยันใหม่", ...p });
}
export const catalog: Program[] = [
  record({ id:"pku-undergraduate", universityId:"pku", university:"Peking University", chineseName:"北京大学 · มหาวิทยาลัยปักกิ่ง", name:"ปริญญาตรีภาษาจีน · เส้นทางสอบเข้า", kind:"admission-route", city:"ปักกิ่ง", source:sources.pku,
    opensAt:"2026-01-01", deadline:"2026-02-28", deadlineNote:"รอบสอบเข้า 2026; วันปิด 23:59 เวลาปักกิ่ง ไม่ใช่เส้นทางยกเว้นสอบ", description:"รับผ่านการสอบข้อเขียนภาษาจีน อังกฤษ และคณิตศาสตร์ ตามด้วยการคัดเลือกรอบถัดไป ระยะเรียน 4–6 ปีตามสาขา",
    academicNote:"จบมัธยมปลาย โดยหลักอายุ 18–25 ปี ณ รอบ 2026; ตรวจสัญชาติและเอกสารเพิ่มเติม ไม่สมัครหลายเส้นทางปริญญาตรีพร้อมกัน", csca:"scholarship", cscaNote:"ผู้สมัคร CSC ต้องมี CSCA; รายวิชาขึ้นกับคณะ",
    feeNote:"ค่าสมัคร 800 CNY; ค่าเรียนรอประกาศอนุมัติ", documents:[...documents,"Personal statement และวิดีโอแนะนำตัว","เตรียมสอบข้อเขียนและการคัดเลือกรอบถัดไป"],
    scholarships:[{name:"PKU / Beijing Government Scholarship",coverage:"ค่าเรียนเต็มหรือบางส่วน ประกัน และค่าครองชีพตามประเภททุน",conditions:"พิจารณาจากผลคัดเลือก ต้องทบทวนทุนรายปี ไม่รับประกันได้รับทุน",deadline:"",route:"มหาวิทยาลัยพิจารณา ไม่ต้องสมัครทุนนี้แยก",source:sources.pku}],
  }),
  record({ id:"fudan-data-science", universityId:"fudan", university:"Fudan University", chineseName:"复旦大学 · มหาวิทยาลัยฟู่ตั้น", name:"Data Science and Big Data Technology", city:"เซี่ยงไฮ้", source:sources.fudan, language:"English", subject:"คอมพิวเตอร์และข้อมูล", years:4,
    ielts:6.5, csca:"required", cscaNote:"CSCA คณิตศาสตร์และฟิสิกส์ เป็นภาษาอังกฤษ; ต้องตรงรอบสอบที่รับ", opensAt:"2026-02-23", deadline:"2026-03-06", deadlineNote:"รอบสอง 2026; รอบแรก 1–15 มกราคม 2026", description:"หลักสูตร UIPDB ภาษาอังกฤษ เน้นสถิติ คอมพิวเตอร์ และการประยุกต์ข้อมูล",
    languageNote:"IELTS 6.5 หรือผลสอบทางเลือกตามประกาศ; อาจยกเว้นเมื่อโรงเรียนสอนวิชาหลักเป็นอังกฤษ", documents:[...documents,"ใบคะแนน CSCA คณิตศาสตร์และฟิสิกส์"],
    reviewNote:"ยืนยันชื่อหลักสูตร ภาษา ระยะเรียน IELTS และรอบสมัคร; ยังไม่ยืนยันค่าเรียนและทุนที่ใช้กับ UIPDB", scholarships:[],
  }),
  record({ id:"sjtu-engineering", universityId:"sjtu", university:"Shanghai Jiao Tong University", chineseName:"上海交通大学 · มหาวิทยาลัยเซี่ยงไฮ้เจียวทง", name:"Global College · Engineering", kind:"admission-route", city:"เซี่ยงไฮ้", source:sources.sjtu, language:"English", subject:"วิศวกรรม", years:4, ielts:6, tuition:120000,
    feeNote:"ประมาณการค่าเรียน GC ปี 2026: 120,000 CNY/ปี; ไม่รวมหอพักและค่าครองชีพ", description:"เส้นทางปริญญาตรีวิศวกรรมของ Global College ต้องเลือกสาขาและรูปแบบการเรียนตามประกาศ", academicNote:"ต้องมีวุฒิมัธยมปลายและผลสอบวิชาการที่มหาวิทยาลัยรับ หรือสอบเข้าของ SJTU; ตรวจข้อกำหนดรอบปัจจุบัน", languageNote:"IELTS 6 ขึ้นไป มีข้อยกเว้นเฉพาะตามผลสอบและประวัติการเรียน",
    scholarships:[{name:"SJTU First / Second / Third-Class Scholarship",coverage:"ค่าเรียน 100% / 50% / 25%; ชั้นหนึ่งมีค่าครองชีพ 2,500 CNY/เดือน และช่วยค่าที่พัก 1,000 CNY/เดือน พร้อมประกัน",conditions:"ระยะ 4 ปีตามประกาศ 2026; ต้องได้รับเข้าเรียน ไม่รับทุนอื่นซ้อน และผ่านการคัดเลือก",deadline:"",route:"ตรวจการพิจารณาทุนกับฝ่ายรับสมัคร GC",source:"https://gc.sjtu.edu.cn/admission/international-undergraduate-admission/fees-and-scholarships/"}],
  }),
  record({ id:"zju-chinese-undergraduate", universityId:"zju", university:"Zhejiang University", chineseName:"浙江大学 · มหาวิทยาลัยเจ้อเจียง", name:"ปริญญาตรีภาษาจีน · หลายสาขา", kind:"admission-route", city:"หางโจว", source:sources.zju,
    description:"เลือกสาขาจากบัญชีหลักสูตรภาษาจีน เกณฑ์ HSK และค่าเรียนขึ้นกับสาขา", csca:"required", cscaNote:"ต้องส่ง CSCA ตั้งแต่ปีการศึกษา 2026/27; รายวิชาและภาษาตามบัญชีหลักสูตร", academicNote:"จบมัธยมปลาย อายุต่ำกว่า 25 ปีตามประกาศ; กรณีต่ำกว่า 18 ปีต้องมีเอกสารผู้ปกครอง", documents:[...documents,"ใบคะแนน CSCA","Personal statement ประมาณ 800 คำ","จดหมายแนะนำสองฉบับ"],
    scholarships:[{name:"Zhejiang Government Scholarship",coverage:"20,000 CNY ระยะหนึ่งปี สามารถสมัครต่อได้ตามผลงาน",conditions:"เฉพาะปริญญาตรีภาษาจีน ไม่ถือทุนอื่นพร้อมกัน",deadline:"",route:"แนบแบบสมัครทุนในระบบมหาวิทยาลัย",source:"https://iczu.zju.edu.cn/admissions/2022/0530/c68875a2568326/page.htm"}], reviewNote:"หน้าทุนระบุปีในช่วงสมัครขัดกัน จึงยังไม่ยืนยันวันปิดทุน; ตรวจสาขาและกำหนดเวลาโดยตรง",
  }),
  record({ id:"xmu-chinese-humanities", universityId:"xmu", university:"Xiamen University", chineseName:"厦门大学 · มหาวิทยาลัยเซี่ยเหมิน", name:"ปริญญาตรีภาษาจีน · มนุษยศาสตร์และธุรกิจ", kind:"admission-route", city:"เซี่ยเหมิน", source:sources.xmu, subject:"มนุษยศาสตร์และธุรกิจ", hskLevel:5,hskScore:210,
    opensAt:"2025-12-01",deadline:"2026-05-10",deadlineNote:"วันปิดสำหรับทุนส่วนตัว; ทุนมหาวิทยาลัยปิด 10 เมษายน 2026", csca:"required",cscaNote:"คณิตศาสตร์และภาษาจีนวิชาการ; ตรวจรายวิชาเพิ่มเติมตามสาขา",description:"เส้นทางมนุษยศาสตร์ เศรษฐศาสตร์ บริหาร กฎหมาย และศิลปะ; สาขาภาษาจีนมีเกณฑ์แยก",academicNote:"จบมัธยมปลาย อายุทั่วไป 18–30 ปี ณ 1 กันยายน 2026; ผู้สมัครทุนต้องผ่านเกณฑ์อายุของทุนนั้น",feeNote:"ค่าสมัคร 400 CNY; ค่าเรียนแตกต่างตามสาขา",documents:[...documents,"ใบคะแนน CSCA","จดหมายแนะนำหนึ่งฉบับ","Personal statement อย่างน้อย 800 คำ","ตรวจรายการใบรับรองสุขภาพและหลักฐานการเงินในประกาศ"],
    scholarships:[{name:"XMU New International Students Scholarship",coverage:"ยกเว้นค่าเรียนสำหรับปริญญาตรี โควตา 5 คนตามประกาศ 2026",conditions:"อายุต่ำกว่า 25 ปี; หลักสูตรภาษาจีนตามบัญชีทุน; ทบทวนสิทธิรายปี",deadline:"2026-04-10",route:"อัปโหลดแบบสมัครทุนที่ลงนามในระบบมหาวิทยาลัย",source:"https://admissions.xmu.edu.cn/Scholarships/Xiamen_University_Scholarships.htm"}],
  }),
  record({ id:"tongji-chinese-language", universityId:"tongji", university:"Tongji University", chineseName:"同济大学 · มหาวิทยาลัยถงจี้", name:"Chinese Language · Economics & Trade / Teaching", city:"เซี่ยงไฮ้", source:sources.tongji, subject:"ภาษาและการศึกษา", hskLevel:4,hskScore:180,languageValidityYears:2,
    opensAt:"2026-01-10",deadline:"2026-03-31",deadlineNote:"รอบปริญญาตรี 2026 เวลาปักกิ่ง",csca:"required",cscaNote:"ต้องส่ง CSCA ก่อนสมัคร; ตรวจรายวิชาตามบัญชีสาขา",description:"เข้าปีหนึ่งสาขาภาษาจีนของ International School มีแนวทางเศรษฐกิจการค้าและการสอนภาษาจีน", academicNote:"ต้องจบมัธยมปลายแบบเต็มเวลา; ไม่รับวุฒิเทียบเท่าหรือเรียนออนไลน์ตามประกาศ; สมัครหนึ่งสาขา",documents:[...documents,"ใบคะแนน CSCA","Personal statement ตามแบบมหาวิทยาลัย","ใบรับรองสุขภาพตามอายุเอกสารที่กำหนด"],
    scholarships:[{name:"Shanghai Government Scholarship / CSC Type A",coverage:"ทุนสำหรับปริญญาตรีภาษาจีน รายการสนับสนุนขึ้นกับประเภททุน",conditions:"อายุผู้สมัครทุน 18–25 ปีตามประกาศ; ต้องตรวจเงื่อนไขของทุนนั้น",deadline:"",route:"CSC Type A ผ่านหน่วยงานประเทศต้นทาง; ทุนเซี่ยงไฮ้ผ่านมหาวิทยาลัย",source:sources.tongji}],
  }),
  record({ id:"ecnu-chinese-undergraduate", universityId:"ecnu", university:"East China Normal University", chineseName:"华东师范大学 · มหาวิทยาลัยหัวตงนอร์มอล", name:"ปริญญาตรีภาษาจีน · หลายสาขา", kind:"admission-route", city:"เซี่ยงไฮ้", source:sources.ecnu,
    description:"เส้นทางปริญญาตรีภาษาจีน เกณฑ์รับสมัครขึ้นกับสาขา ส่วนเกณฑ์ HSK ของทุนต้องตรวจแยก",documents:[...documents,"ตรวจวิชา CSCA ในบัญชีหลักสูตร"],
    scholarships:[{name:"ECNU Excellent Freshmen Scholarship",coverage:"ค่าครองชีพ 2,500 CNY/เดือน รวม 12 เดือนในปีแรก",conditions:"อายุต่ำกว่า 25 ปี ผลการเรียนดี HSK 5 ตามเกณฑ์ประกาศ; ไม่ครอบคลุมหลักสูตรอังกฤษหรือหลักสูตรร่วม และไม่รับทุนซ้อน",deadline:"2026-04-30",route:"ยื่นในระบบ ECNU และรอผลคัดเลือกทุนหลังผลรับเข้าศึกษา",source:"https://lxs.ecnu.edu.cn/en_scholarship_undergraduate_excellent_freshmen_scholarship/list.htm"}],
  }),
  record({ id:"blcu-chinese-language", universityId:"blcu", university:"Beijing Language and Culture University", chineseName:"北京语言大学 · มหาวิทยาลัยภาษาและวัฒนธรรมปักกิ่ง", name:"Chinese Language", city:"ปักกิ่ง", source:sources.blcu, subject:"ภาษาและการศึกษา", intake:"2027-03", hskLevel:4,hskScore:180,tuition:25800,feeYear:"หน้าเกณฑ์ปัจจุบัน",feeNote:"25,800 CNY/ปีตามหน้าเกณฑ์ที่ตรวจ; ยืนยันอัตราสำหรับมีนาคม 2027 อีกครั้ง",description:"สาขาภาษาจีนเปิดรอบมีนาคมและกันยายนตามสัญลักษณ์ในบัญชีหลักสูตร",csca:"required",cscaNote:"ผู้สมัครปริญญาตรีตั้งแต่ฤดูใบไม้ร่วง 2026 ต้องมี CSCA",academicNote:"วุฒิมัธยมปลายหรือเทียบเท่า; ผู้มีอายุต่ำกว่า 18 ปีต้องขออนุญาตและมีเอกสารผู้ปกครอง",reviewNote:"มีประกาศวันปิดทุนมีนาคม 2027 แล้ว แต่หน้าเกณฑ์วันสมัครเรียนมีปีขัดกัน จึงยังไม่ยืนยันวันปิดสมัครเรียน",documents:[...documents,"ใบคะแนน CSCA","จดหมายแนะนำ","หลักฐานผู้รับรองและเอกสารอื่นตามประกาศ"],
    scholarships:[{name:"Beijing International Students Scholarship",coverage:"ค่าเรียนปีแรก ไม่รวมค่าใช้จ่ายอื่น",conditions:"ผู้สมัครปริญญาตรีโดยหลักอายุไม่เกิน 30 ปีตามเกณฑ์ประกาศ; ต้องได้รับอนุมัติทุน",deadline:"2027-01-12",route:"แนบแบบสมัครทุนสำหรับนักศึกษาใหม่ในระบบ BLCU; รอบมีนาคม 2027",source:"https://admission.blcu.edu.cn/en/2023/1219/c1156a2681/page.htm"}],
  }),
  record({ id:"uibe-international-business", universityId:"uibe", university:"University of International Business and Economics", chineseName:"对外经济贸易大学 · มหาวิทยาลัยเศรษฐศาสตร์และธุรกิจระหว่างประเทศ", name:"International Business", city:"ปักกิ่ง", source:sources.uibe,language:"English",subject:"ธุรกิจและเศรษฐศาสตร์",years:4,ielts:6,tuition:49750,feeYear:"หน้าเกณฑ์ปัจจุบัน",feeNote:"49,750 CNY/ปี; ค่าสมัคร 660 CNY; ยืนยันอัตรารอบที่จะสมัคร",intake:"รอบทั่วไป",deadlineNote:"เว็บไซต์ระบุรอบใบไม้ผลิ 20 ต.ค.–31 ธ.ค. และใบไม้ร่วง 20 มี.ค.–30 มิ.ย. ของแต่ละปี ต้องยืนยันรอบ 2027",csca:"required",cscaNote:"ต้องส่ง CSCA วิชาคณิตศาสตร์",description:"หลักสูตรธุรกิจระหว่างประเทศภาษาอังกฤษ ระยะสี่ปี",languageNote:"IELTS 6.0 หรือ TOEFL 86 หรือหลักฐานทางเลือกที่ประกาศรับ",documents:[...documents,"ใบคะแนน CSCA คณิตศาสตร์","ตรวจหลักฐานผู้รับรองและการเงิน"],reviewNote:"หน้าเกณฑ์ไม่ระบุปีเฉพาะ; ยังไม่ยืนยันทุนสำหรับหลักสูตรภาษาอังกฤษนี้",
  }),
  record({ id:"sdufe-international-trade", universityId:"sdufe", university:"Shandong University of Finance and Economics", chineseName:"山东财经大学 · มหาวิทยาลัยการเงินและเศรษฐศาสตร์ซานตง", name:"International Economics and Trade", city:"จี่หนาน",source:sources.sdufe,language:"English",subject:"ธุรกิจและเศรษฐศาสตร์",ielts:5.5,deadline:"2026-06-20",deadlineNote:"วันปิดสมัครตามประกาศทุนโครงการ 2026",feeNote:"ค่าเรียนรวมที่พักห้องคู่ 12,000 CNY/ปี; ไม่แยกค่าเรียน จึงไม่ใช้เป็นค่าเรียนเดี่ยว",description:"หลักสูตรอังกฤษในโครงการทุนเฉพาะ เปิดชั้นเรียนเมื่อมีนักศึกษาอย่างน้อย 20 คน",academicNote:"จบมัธยมปลาย สัญชาติอื่นที่ไม่ใช่จีน; ผู้ขอทุนต้องไม่รับทุนอื่นซ้อน",csca:"scholarship",cscaNote:"CSCA เป็นเอกสารประกอบการพิจารณาทุนระดับสูงในประกาศนี้",languageNote:"IELTS อย่างน้อย 5.5 หรือเทียบเท่า",documents:[...documents,"หลักฐานการเงิน","ประวัติส่วนตัวสำหรับผู้ไม่ได้เพิ่งจบมัธยม"],
    scholarships:[{name:"English-taught Undergraduate Special Scholarship",coverage:"ทุนสูงสุดยกเว้นค่าเรียนและหอพักห้องคู่; ไม่รวมค่าสมัครและประกัน",conditions:"ปีที่สองเป็นต้นไปพิจารณาจากผลการเรียนและความประพฤติ; ห้ามรับทุนอื่นซ้อน",deadline:"2026-06-20",route:"สมัครผ่านระบบนักศึกษาต่างชาติ SDUFE",source:sources.sdufe}],
  }),
];

export const sourceRegistry = [...new Set(catalog.flatMap(p => [p.source, p.requirementsSource, ...p.scholarships.map(s=>s.source)]))].map((url,i)=>({id:`source-${String(i+1).padStart(2,"0")}`,url,universityIds:catalog.filter(p=>[p.source,p.requirementsSource,...p.scholarships.map(s=>s.source)].includes(url)).map(p=>p.universityId)}));
